# 1. Database URL - Intha port-la thaan MySQL run aagum
spring.datasource.url=jdbc:mysql://localhost:3306/smart_ecommerce_db

# 2. Unga Workbench username and password (Idhai mathikkonga)
spring.datasource.username=root
spring.datasource.password=root

# 3. Hibernate logic - Yen?
# 'update' nu kudutha, namma Java-la ezhutha pora 'Table' design-ah 
# MySQL-la ithuve automatic-ah create pannidum.
spring.jpa.hibernate.ddl-auto=update
# Intha rendu line-ah extra-va sethukkonga
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# 4. SQL Queries-ah log-la paaka (Debugging-ku use aagum)
spring.jpa.show-sql=true